stages: 
  - test
#  - deploy

image: tyteck/php4core

cache:
  paths:
  - vendor/

before_script:
# - bash ci/requirements.sh > /dev/null
# SSH part
- 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
- eval $(ssh-agent -s)
- echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
- mkdir -p ~/.ssh && chmod 600 ~/.ssh
- '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

test:
  stage: test
  only:
    refs:
      - master
  script:
  - composer install
  - phpunit --configuration phpunit.xml tests/Quick/CategoriesTest.php

  services:
  - mysql

  variables:
    # Configure mysql service (https://hub.docker.com/_/mysql/)
    MYSQL_DATABASE: "pmtests"
    MYSQL_ROOT_PASSWORD: "$MYSQL_ROOT_PASSWORD"

  connect:
    image: mysql
    only:
      refs:
        - master
    script:
    - echo "SELECT 'OK';" | mysql --user=root --password="$MYSQL_ROOT_PASSWORD" --host=mysql "$MYSQL_DATABASE"


#deploy: 
#  stage: deploy
#  only:
#    refs:
#      - master
#  environment:
#    name: vps2
#  script:
#  - ssh vps591114.ovh.net "cd /home/www/core.podmytube.com && git pull"
