version: '3.3'
services:
  node:
    command: bash -c "npm install && npm run production"  
  composer:
    command: install --no-dev
  dashboard-pmt:
    expose:
        - "80"
        - "443"
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST:?set it in .env}      
      - LETSENCRYPT_HOST=${VIRTUAL_HOST:?set it in .env}
      - LETSENCRYPT_EMAIL=frederick@podmytube.com
